<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Registration\Module'                        => __DIR__ . '/Module.php',
    'Registration\Controller\RegistrationController' => __DIR__ . '/src/Registration/Controller/RegistrationController.php',
    'RegistrationTest\Framework\TestCase'        => __DIR__ . '/tests/Registration/Framework/TestCase.php',
    'RegistrationTest\SampleTest'                => __DIR__ . '/tests/Registration/SampleTest.php',
);
