<?php echo $this->doctype(); ?>
<?php 

if(isset($_SESSION['username']))
{
 $username = $_SESSION['username'];
}
else 
{
	$username = "";
} 
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '.$this->translate('BlogApplication'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath().'/js/jqueryui/jquery-ui.min.css')
                ->prependStylesheet($this->basePath().'/js/jqueryui/jquery-ui.structure.min.css')
                ->prependStylesheet($this->basePath().'/js/jqueryui/jquery-ui.theme.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath().'/js/jqueryui/jquery-ui.min.js')
                ->appendFile($this->basePath().'/js/jquery.tablesorter.js')
                ->appendFile($this->basePath().'/js/searchPlugin.js')
                ->appendFile($this->basePath().'/js/bootbox.min.js')
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
            
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
<!--                 Add the zend framework logo here  -->
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('blog',array('action'=>'index')) ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('blog',array('action'=>'newpost')) ?>"><?php echo $this->translate('Newpost') ?></a></li>
                        <?php if(!isset($_SESSION['username'])):?>
                    	<li><a href="<?php echo $this->url('registration',array('action'=>'register')) ?>"><?php echo $this->translate('Register') ?></a></li>
                    	<?php endif;?>
                    	<li><a href="<?php echo $this->url('blog',array('action'=>'myposts')) ?>"><?php echo $this->translate('Myposts') ?></a></li>
                        <li><a href="<?php echo $this->url('blog',array('action'=>'addtask')) ?>"><?php echo $this->translate('Addtask') ?></a></li>
                        <?php if(isset($_SESSION['username'])):?>
                        <li class="nav-welcome"><a href="<?php echo $this->url('blog',array('action'=>'userprofile','id'=>$_SESSION['userid'])) ?>"> <?php echo "  "; echo $username;?>:</a></li>
                        <?php endif;?>
                        <li class="nav-logout"> <a href="<?php echo (isset($_SESSION['username']) ? $this->url('registration',array('action'=>'logout')) : $this->url('registration',array('action'=>'login')))   ?>"><?php echo (isset($_SESSION['username']) ? 'Logout' : 'Login') ?></a></div></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>											
        </nav>
        <div class="container-fluid">
        <div class ="row">
        <div class="col plr-60">
			<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
            </div>
            </div>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
    <style>
    	.plr-60{
    	padding-left:80px!important;
    	padding-right:80px!important;
    	padding-top:80px!important;
    	}
    	.nav-welcome{
    		position: absolute!important;
    	    right: 200px;
    	    top:0px;
/*     	    top:20px; */
/*     	    border:0px; */
/*     	    background-color:none; */
    	}
    	.nav-logout{
    	    position: absolute !important;
    	    right: 150px;
    	    top:0px;
            
    	}
    	
    </style>
</html>
