

<?php echo $this->form()->openTag($form);?>
 
 
  <div class="row" style="padding-left:26px;">
  <div class="panel-heading"></div>
  <div class="col-md-12 jumbotron padset">
        <h3 style="padding-left: 16px; margin-top: 0px;">Add New Task</h3>
	    <div class="col-md-4">
	    <?php echo $this->formrow($form->get('taskname'));?>
        </div>
        <div class="col-md-4">
	    <?php echo $this->formRow($form->get('duedate'));?> 
        </div>
        <div class="col-md-4">
	       <?php
	           echo $this->forminput($form->get('submit'));
	       ?> 
        </div>
<!--     </div> -->
<!--       </div> -->
    </div>
	</div>
  

<div class="row">
<!-- Starts right Block -->
<div class="col-md-6">
<div class="panel panel-success style">
<h3 style="padding-left: 5px">Tasks in Process</h3>

<table class="table table-striped table" id="firsttable" border='1'>

<thead>
    <tr>
      <th class="header-table" scope="col">Task Name</th>
      <th class="header-table" scope="col">Due Date</th>
      <th  class="header-table" class="tbl-col" scope="col">Completed</th>
    </tr>
 </thead>
    <?php foreach($results as $result):?>
          
    <tr>
    <td class="taskname">
   <?php 
   echo $result->getTaskname();?>
   </td>
    
   <td class="duedate">
   <?php 
//    $date=$result->getDuedate();
   $dat=$result->getDuedate();
   $duedated = $this->dateFormat($dat, IntlDateFormatter::LONG);
   $date=(array)$result->getDuedate();
   $duedate = $this->dateFormat($date, IntlDateFormatter::LONG);
   $datecreate=(array)date_create(date('d-m-Y'));
   $currentdate = $this->dateFormat($datecreate, IntlDateFormatter::LONG);
//    explode('-',$date['date']);
   $date = explode('-',$date['date'])[0].''.explode('-',$date['date'])[1].''.explode('-',$date['date'])[2];
//    print_r($date);
   $date2 = explode('-',$datecreate['date'])[0].''.explode('-',$datecreate['date'])[1].''.explode('-',$datecreate['date'])[2];
   $a=(int)str_replace(array(' ', ','), '', $date);
   $b=(int)str_replace(array(' ', ','), '', $date2);
   if($b<$a)
   {
   	echo "<span>".$duedated."</span>";
   }
   else
   {
   	echo "<span class='test'>".$duedated."</span>";
   
   }
   ?>
   </td>
   <td>
   <input type="hidden" class="taskid" value="<?php echo $result->getTaskid();?>">
   <?php echo $this->formrow($form->get('taskstatus'));?>
   </td>
   
   </tr>
<?php endforeach; ?>
	</table>
</div>
</div>


<!--starts left block -->

<div class="col-md-6">
<div class="panel panel-success style">
<h3 style="padding-left: 5px">Completed Tasks</h3>
<table class="table table-striped table" id="results" border='1'>
<thead>
    <tr>
        <th class="header-table" scope="col">Task Name</th>
         <th class="header-table" scope="col">Due Date</th>
         <th class="header-table" scope="col">Completed Date</th>
         <th class="header-table" scope="col">Undo Task</th>
    </tr>
  </thead>
    <?php foreach($completed as $result):?>
          
    <tr>
    <td class="undotaskname">
   <?php 
   echo $result->getTaskname();?>
   </td>
    
   <td class="undoduedate">
   <?php $date=$result->getDuedate();?><?php echo $this->dateFormat($date, IntlDateFormatter::LONG);?>
   </td>
   <td>
   <?php $date2=$result->getCompleteddate();?><?php echo $this->dateFormat($date2, IntlDateFormatter::LONG);?>
   </td>
   <td>
   <input type="hidden" class="undoid" value="<?php echo $result->getTaskid();?>">
   <input type="checkbox" checked="true" name="taskstatus2" onchange="undoTask(this)">
   </td>
   </tr>
<?php endforeach; ?>
	</table>
</div>
</div>

</div>

<?php echo $this->form()->closeTag($form);?>

<script>	      
// $("#sub").click( function(){

// 	//alert($("#taskname").val());
// 	  $.ajax(
// 		{
// 		  url: '/blog/addtask',
// 		  data : {'taskname':$("#taskname").val(),'duedate':$("#duedate").val()},
// 	      type: 'POST',
// 	      dataType : 'JSON',
// 		  success: function(data){

			  
		            
// 		  },
// 		    });
// 	});
<!-- </script>  -->
<script>	      
$("#sub").click( function(){
	 var name = $("#taskname").val();
     var date = $("#duedate").val();
     var dataString = {"taskname":name, "duedate":date};
	  $.ajax(
		{
		  url: '/blog/addtask',
		  data : dataString,
	      type: 'POST',
	      dataType : 'JSON',
		  success: function()
		  {
			$('#firsttable tbody').prepend('<tr><td>'
					+name+'</td><td>'+date
			+'</td><td><input type="checkbox" name="taskstatus" onchange="completeTask(this)"><input type="hidden" value="<?php
		    echo $result->getTaskid();?> class="taskid""></td></tr>');	           
		   },
		    });
	});

var completeTask = (obj)=>{
var _selFrow = obj;
var taskName = $(obj).closest('tr').find('.taskname').text();
var date =  $(obj).closest('tr').find('.duedate').text(); 
var taskId = $(obj).closest('tr').find('.taskid').val();
 $(obj).closest('tr').remove();	
 $.ajax(
		{
			  url: '/blog/updatetaskstatus',
			  data : {'id':taskId},
		      type: 'POST',
		      dataType : 'JSON',
			  success: function(cdate)
			  {
			   $('#results tbody').prepend('<tr><td>'
					   +taskName+'</td><td>'+date+'</td><td>'+cdate.date
					   +'</td><td><input type="checkbox" name="taskstatus"  checked="true" onchange="completeTask(this)"><input type="hidden" value="<?php
					    echo $result->getTaskid();?>" class="taskid"></td></tr>');	           
			   },
	 });
}
var undoTask = (obj)=>{
var _selFRow = obj;
var undotaskname = $(obj).closest('tr').find('.undotaskname').text();
var undodate=$(obj).closest('tr').find('.undoduedate').text();
var undoid=$(obj).closest('tr').find('.undoid').val();
$(obj).closest('tr').remove();
// alert("taskid=" +undoid);
$.ajax(
		{
			  url: '/blog/undotaskstatus',
			  data : {'id':undoid},
		      type: 'POST',
		      dataType : 'HTML',
			  success: function(){
			   $('#firsttable tbody').prepend('<tr><td>'
					   +undotaskname+'</td><td>'+undodate
					   +'</td><td><input type="checkbox" name="taskstatus" onchange="completedTask(this)"><input type="hidden" value="<?php 
					   echo $result->getTaskid();?> class="taskid""></td></tr>');	           
		},
	 });
}


</script>

<style>
	   .button-position{
	       position: relative;
           top: 40px;
           width: 80px;
           

/*     padding-bottom: 17px; */
/*     top: 35px; */
}
	   
	   .label-head{
	  position: relative;
           left: 146px;
	   }
	   .tbl-col{
	       width: 81px;
	   }
	   .tbl.check{
	       position: relative;
           right: -23px;
	   } 
	   .table{
		   overflow:hidden;
	/*        overflow-y:scroll; */
	        height: 300px;
	      
	        overflow:auto;
	        white-space: nowrap;
	        display:block;
             }
.header-table{
      width: 260px;
}
.test{
color:red;
}
.style{
  border-color:black;
    border-right-width: 1px;
    border-top-width: 1px;
    border-left-width: 1px;
    border-bottom-width: 1px;
   
    position: relative;
      right: -10px;
    
    

}
.padset{

    padding-left: 17px;
    padding-right: 17px;
    padding-top: 17px;
    padding-bottom: 17px;

}
.pad{
padding-top: 0px;
}
	    
	      </style>