<?php
$title = "Update Post";
?>
 <div class="container">
  <!-- main container starts -->
  
  
  
  
  <h1 style="text-align:center;"><?php echo $this->escapeHtml($title); ?></h1>
  <hr>
  <?php
 $form = $this->form;
 $form->setAttribute('action',$this->url('blog', array('action' => 'edit','id' => $id)));
 $form->get('submit')->setAttribute('value', 'Update');
 $form->setAttribute('enctype','multipart/form-data');
 $form->prepare();
// echo $this->formHidden($form->get('userid'));
 ?>
  
<?php echo $this->form()->openTag($form);?>




        
  
  <div class="container">
  <div class="row">
      <div class="col-md-4 col-xs-12">

    <?php echo $this->formRow($form->get('title')); ?> 
    
    </div>
    <div class="col-md-12 col-xs-12">

    <?php echo $this->formRow($form->get('userphoto')); ?>
    
    
    </div>
  <div class="col col-xs-12">
 <?php echo $this->formRow($form->get('userpost')); ?>
 </div>
 <div class="col-md-2 col-md-offset-8">

    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
 </div>
  <?php
 echo $this->form()->closeTag($form);?>
 </div>
 </div>
