
<?php

 $title = 'Myposts';
 $this->headTitle($title);
 ?>
 <div class="container">
 <?php foreach($myposts as $data): ?>
 <div class="container">
  <div class="row">
    
    <?php if($data->getUserphoto()) : ?>
    <div class="col-md-3 col-sm-3">	
    <a class="nav-link active" id="pills-home-tab"  href="<?php echo $this->url('blog',array('action'=>'readmore','id'=>$data->getBlogid())) ?>" role="tab" aria-controls="pills-home" aria-selected="true"><img src="
    	<?php echo  $this->basePath("img/".$data->getUserphoto());?>" 
    	alt="..." class="img-thumbnail myimg" style="margin-top:25px!important"></a>	
      </div>
    <?php endif; ?>
 
    <div class=" col-md-9 col-sm-9 ">
    <a class="nav-link active" id="pills-home-tab"  href="<?php echo $this->url('blog',array('action'=>'readmore','id'=>$data->getBlogid())) ?>" role="tab" aria-controls="pills-home" aria-selected="true"><h2 style="color: blue"><?php echo $data->getTitle();?></h2></a>
    
  	<h4 class="card-title" style="color: darkgrey"><?php $date=$data->getPostdate();?>Posted on <?php echo $this->dateFormat($date, IntlDateFormatter::LONG,IntlDateFormatter::SHORT, "en_US");?></h4>	
       <p class="card-text"><?php echo substr($data->getuserPost(), 0,300);?></p> 
   
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
    <a class="nav-link active" id="pills-home-tab"  href="<?php echo $this->url('blog',array('action'=>'readmore','id'=>$data->getBlogid())) ?>" role="tab" aria-controls="pills-home" aria-selected="true"><?php echo $this->translate('Read more') ?></a>
  </li>
  </ul>
    </div>
  </div>
  <hr>
</div>
  <?php endforeach; ?> 
</div>

